package com.mobi.mobi;

public enum MobiType {
    MOBI_POCKET(1, "Mobipocket Book"),
    PALM_DOC(3, "PalmDoc Book"),
    AUDIO(4, "Audio"),
    KINDLE_GEN(232, "mobipocket? generated by kindlegen1.2"),
    KF8(248, "KF8: generated by kindlegen2"),
    NEWS(257, "News"),
    NEWS_FEED(258, "News_Feed"),
    NEWS_MAG(259, "News_Magazine"),
    PICS(513, "PICS"),
    WORD(514, "WORD"),
    XLS(515, "XLS"),
    PPT(516, "PPT"),
    TEXT(517, "TEXT"),
    HTML(518, "HTML");

    MobiType(int n, String desc) { value = n; name = desc; }
    public final int value;
    public final String name;
}